[[redirects]]
  from = "/carousel"
  to = "Componentes/carousel/carousel.html"

[[redirects]]
  from = "/footer"
  to = "Componentes/footer/footer.html"

[[redirects]]
  from = "/index"
  to = "index.html"

[[redirects]]
  from = "/Formulario"
  to = "Paginas/Formulario/Formulario.html"

[[redirects]]
  from = "/Tablas"
  to = "Paginas/Tablas/Tablas.html"

[[redirects]]
  from = "/Video"
  to = "Paginas/Video/Video.html"

[[redirects]]
  from = "/Principal"
  to = "Paginas/Principal/Principal.css"
